### ISSUE TITLE
Todo list with Redux

### ISSUE THREAD

**Issue by zfanli** [zfanli/blueprint#2]
技术选型，目标 Redux。
制作一个基于 Redux 管理控制数据流的 DEMO。
目前预计 Deadline 是 4.29（周日）。

Task list:
* Todo list UI design ( deadline 4.27)
* Create app use React and Redux ( deadline 4.29)

**Comment by southwang** [comment]
Todo list UI design ( deadline 4.27), accepted.

**Comment by CRitsu** [comment]
@southwang Here are some details.

The Todo list should has these feature/component:

* Add todos, means there should has an input box for this feature
* Show active todos, the todos which is incomplete
* Show past todos, which completed
* Show past todos switch button, control the past todos should be shown or not
* Filter, determine which todo should be shown

Above is the basic contents, and you can add anything more what you want.

Finally,  attention deadline and DO NOT be overdue pls! 

PS: Only smart phone, it's just a demo for technology selection not real app.

**Comment by southwang** [comment]
( ๑ŏ ﹏ ŏ๑ )



发自我的小米手机
在 "C.Rick" <notifications@github.com>，2018年4月26日 上午12:32写道：

@southwang<https://github.com/southwang> Here are some details.

The Todo list should has these feature/component:

  *   Add todos, means there should has an input box for this feature
  *   Show active todos, the todos which is incomplete
  *   Show past todos, which completed
  *   Show past todos switch button, control the past todos should be shown or not
  *   Filter, determine which todo should be shown

Above is the basic contents, and you can add anything more what you want.

Finally, attention deadline and DO NOT be overdue pls!

PS: Only smart phone, it's just a demo for technology selection not real app.

**Comment by CRitsu** [comment]
OVERDUE

时间重新安排：

* Todo list UI design ( deadline 5.4)
* Create app use React and Redux ( deadline 5.6)

实际上延期一星期。

Attention the new deadline！

**Comment by CRitsu** [comment]
**OVERDUE TWICE**:anger: :anger: 

- [X] Todo list UI design (deadline 5.4 ) - actually 5.7
- [ ] Create app use React and Redux (deadline 5.6) - delay to 5.13

**Comment by zfanli** [comment]
* 被琐事耽误
* 现实上遇到一些问题

延迟到这周结束。

**Comment by zfanli** [comment]
The actually completed date is 2018.5.19 1:52 AM.
